### ISSUE TITLE
Hidden Tab Redirect Not Working in iOS Beta

### ISSUE THREAD

**Issue by mrgadget** [maykar/compact-custom-header#205] opened 2019-09-21 11:39 UTC
## Describe the issue:
Moved to the HA iOS Beta app and CCH no longer redirects away from my hidden 'conig' tab (tab 0). ie, on a fresh load tab 0 content is shown (when it shouldn't be on a mobile device).  The correct icons are hidden in the header - which indicates the correct conditions block is being hit, it's just behaving like the 'redirect' option isn't working.

Not a major issue - just thought you'd like to know about it.

## Config YAML:

```yaml
cch:
  background: '#003A99'
  clock_am_pm: false
  clock_date: false
  clock_format: '24'
  disable: false
  exceptions:
    - conditions:
        user: Ben
        user_agent: Mobile
      config:
        hide_tabs: '0,1,2,6'
    - conditions:
        user: Ben
      config:
        hide_tabs: '6'
        menu: show
        options: show
  header: true
  hide_tabs: '0,1,2'
  main_config: true
  menu: hide
  options: hide
  redirect: true
  voice: hide
```
## HA and/or Browser Error:

No errors, able to simply browse to another tab, then can't get back again (expected).

## Versions and Browser:

HA 0.97.2
CCH 1.3.1
iOS Beta App
YAML or Storage Mode? No idea...

**Comment by maykar** [comment] 2019-09-21 12:36
Will check this out later this week. I'll be getting an iOS device and will finally be able to test iOS issues. I can confirm that redirects are working on PC and Android at the moment.

Is there any reason you're using CCH version 1.3.1? Have you tried the latest (1.3.8)?

**Comment by mrgadget** [comment] 2019-09-22 00:10
No worries - not at all urgent.

I use custom updater and 1.3.1 is still shown as the latest version available

![image](https://user-images.githubusercontent.com/700522/65380561-ec5a7d00-dd31-11e9-9572-b3f234aaf1ea.png)

**Comment by maykar** [comment] 2019-09-22 01:31
Custom Updater is, ironically, [no longer being updated](https://github.com/custom-components/custom_updater#partial-deprecation). The [HACS component](https://github.com/custom-components/hacs) has taken it's place. Custom Updater will no longer show the latest version for CCH due to changes in it's file structure. I would suggest either moving to HACS or installing CCH manually.

I would be interested to know if this issue persists after updating to the latest CCH.

**Comment by maykar** [comment] 2019-09-22 01:31
https://github.com/custom-components/hacs

**Comment by mrgadget** [comment] 2019-09-25 12:13
Thanks for pointing that one out - I've now updated HA (0.99.2) and installed HACS and CCH 1.3.8, seems the same.  Oddly, if I pull down (which does a UI refresh in the beta version)50-60% of the time I'll get the page skipped correctly, the rest it will show page 0.  It's inconsistent - sorry, hard to troubleshoot I know.  Perhaps just park this one until you have an iOS device.

It might also be worth noting I'm on iOS 13.1 (was on 13.0 when I first reported this issue).

**Comment by maykar** [comment] 2019-09-25 21:01
Now have an iPad for testing! 

Tweaked default_tab a bit to address this in the latest release (1.3.9) let me know if it helps. Thanks!

**Comment by mrgadget** [comment] 2019-09-26 01:54
Excellent! Installed 1.4.0.  After some intensive refreshing I only managed to get it to display the wrong tab (0) twice (out of probably 30 refreshes) - which I'm happy to call loading anomalies.

An application force-close and re-launch reliably results in the correct tab being shown.

Thanks for sorting this (and pointing me down the HACS route).

**Comment by maykar** [comment] 2019-09-26 02:16
I'll consider that a win as well and will keep an eye on it as new versions of the iOS client come out. Closing this for now as the iOS app is still beta and redirects are stable on all other clients (as far as I am aware).

**Closed as completed by maykar** 2019-09-26 02:16 UTC
