### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Dinth** [maykar/compact-custom-header#5] opened 2018-12-14 07:09 UTC
When installed on 0.84.1, the header bar stays in place, but none of the lovelace page contents below are shown. Im also getting this error in the log:

`(...)/local/custom_lovelace/compact-custom-header/compact-custom-header.js?v0:13:51 Uncaught TypeError: Cannot read property 'split' of undefined`

**Comment by maykar** [comment] 2018-12-14 12:09
This is a duplicate of #6. Also, the type error was fixed in version 0.0.7.

**Closed as completed by maykar** 2018-12-14 12:09 UTC
Labels: duplicate

**Comment by Dinth** [comment] 2018-12-14 20:03
> Also, the type error was fixed in version 0.0.7.

Hi Maykar. Im not sure when 0.0.7 was orginally released, but i just installed compact-custom-header for the first time yesterday, literally just before posting my issue. Today i updated it to the latest version on github and im still getting that error.

**Comment by maykar** [comment] 2018-12-14 20:45
So this portion of the error tells me what line in the code the error happened on:
```
compact-custom-header.js?v0:13:51 
```
line 13 character 51

The code that "splits" is no longer on that line. This tells me that the version you're using is one that has split on that line (an older one).

0.0.7 (the latest version) was released yesterday

If you're running home assistant version 0.84 or greater, keep in mind that there are issues with custom-updater if you use it.

**Comment by maykar** [comment] 2018-12-14 20:50
So, if it is the exact same error you are getting, you most likely need to read through and follow the "Important Notes" section of the readme and/or the upgrade instructions in the installation section.

Specifically:
* Clear cache or full page refresh or maybe even close any open HA tabs/windows.
* Add to the version number at the end of the resources url.
